export const theme = {
  colors: {
    wine_purple: '#45007b',
    wine_mid_purple: '#46007bca',
    wine_light_purple: '#faf7ff',
    bg_white: '#ffffff',
    bg_white_gray: '#f8f8f8',
    bg_lightgray: '#eeeeee',
    border_gray: '#b1b1b1d2',
    border_lightgray: '#dadada',
    text_white: '#ffffff',
    text_black: '#1E1E1E',
    text_darkgray: '#2f2f2f',
    text_gray: '#6E6E6E',
  },
  fontSize: {
    xs: '10px',
    sm: '12px',
    base: '14px',
    md: '16px',
    lg: '18px',
    xl: '20px',
    xxl: '24px',
    logo: '28px',
  },
} as const;
